Karena yang akan digunakan hanya kolom full text atau isi ulasan maka disimpan file csv dengan isi kolom full text untuk meringankan beban komputasi

In [1]:
import os
import pandas as pd

# Membaca file dan menampilkan 5 data pertama
df = pd.read_csv("../../ScrapingData/hasilScrapUlasanAplikasiShopeepay.csv")
print(df.head())

                              Review id         Username  Rating  \
0  cadcde91-9403-4c8d-b8b1-fd0105c9587e  Pengguna Google       4
1  195cc76b-1bee-4484-975e-689deea11a7e  Pengguna Google       5
2  cdd95223-f59e-44d8-af2f-847a86e9380a  Pengguna Google       4
3  ca8b22c3-b610-44d7-b407-6c52fb0edc98  Pengguna Google       5
4  46ac09dc-dd99-4a3d-ade5-f3aebc0979cf  Pengguna Google       5

                                         Review text                 Date
0  Di coba dulu. Kalau memuaskan, bisa diberikan ...  2025-12-30 21:04:03
1                                       mantap murah  2025-12-30 21:03:07
2                                            mantabb  2025-12-30 20:56:16
3                  bisa bayar pulsa dan juga belanja  2025-12-30 20:50:07
4                kenapa pas transaksi gagal mulu min  2025-12-30 20:47:44

In [2]:
df = df[["Review text"]]
print(df.tail())

                               Review text
14995        Alhamdulillah sangat terbantu
14996  sangat suka dan ini sangat membantu
14997                                 baik
14998                                 baik
14999                         lumayan baik

In [3]:
# Tentukan path folder tujuan
folder_tujuan = 'DatasetPreprocessShopeepay' 

# Pastikan folder tujuan sudah ada, jika belum maka buat folder tersebut
# Ini adalah langkah yang baik untuk menghindari error
if not os.path.exists(folder_tujuan):
    os.makedirs(folder_tujuan)

# Gabungkan path folder dengan nama file yang diinginkan
path_output = os.path.join(folder_tujuan, 'Tahap1IsiUlasan.csv')

# Simpan DataFrame ke path yang sudah ditentukan
df.to_csv(path_output, index=False, encoding='utf-8')

print(f"File berhasil disimpan di: {path_output}")

# Tetap tampilkan info DataFrame setelah menyimpan
df.info()

File berhasil disimpan di: DatasetPreprocessShopeepay\Tahap1IsiUlasan.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Review text  15000 non-null  object
dtypes: object(1)
memory usage: 117.3+ KB

## Hapus data duplikat dan data kurang dari 3 huruf

In [4]:
import pandas as pd
import os

# --- PENGOLAHAN FILE ---

# 1. Tentukan nama file CSV yang akan diproses
nama_file_input = 'DatasetPreprocessShopeepay/Tahap1IsiUlasan.csv' # GANTI DENGAN NAMA FILE ANDA

# Pastikan file ada sebelum melanjutkan
if not os.path.exists(nama_file_input):
    print(f"Error: File tidak ditemukan di '{os.path.abspath(nama_file_input)}'")
else:
    # 2. Langsung baca satu file CSV ke dalam DataFrame
    print(f"Membaca file: '{nama_file_input}'")
    data = pd.read_csv(nama_file_input)

    print(f"\nJumlah baris sebelum menghapus duplikat: {len(data)}")

    # 3. Hapus baris duplikat berdasarkan kolom 'full_text'
    data.drop_duplicates(subset=['Review text'], inplace=True, keep='first')

    print(f"Jumlah baris setelah menghapus duplikat: {len(data)}")

    # --- PENYIMPANAN FILE ---

    # 4. Tentukan nama folder dan file output
    folder_tujuan = 'DatasetPreprocessShopeepay'
    
    # Tentukan path lengkap untuk file output
    nama_file_output = 'Tahap2HapusDuplikat.csv'
    path_output = os.path.join(folder_tujuan, nama_file_output)

    # 5. Simpan DataFrame yang sudah bersih ke file baru
    data.to_csv(path_output, index=False, encoding='utf-8')

    print(f"\nSukses! Duplikat telah dihapus dan file disimpan di:")
    print(f"'{path_output}'")

Membaca file: 'DatasetPreprocessShopeepay/Tahap1IsiUlasan.csv'

Jumlah baris sebelum menghapus duplikat: 15000
Jumlah baris setelah menghapus duplikat: 9159

Sukses! Duplikat telah dihapus dan file disimpan di:
'DatasetPreprocessShopeepay\Tahap2HapusDuplikat.csv'

In [5]:
import pandas as pd
import re
import os

# 1. Fungsi untuk menghapus kata dengan huruf <= 3
def hapus_kata_pendek(data):
    """
    Menghapus kata-kata yang panjang hurufnya <= 3.
    Contoh:
    'aku di rumah' -> 'rumah'
    'ini bagus banget' -> 'bagus banget'
    """
    if not isinstance(data, str):
        return ''
    
    # Hapus tanda baca supaya tidak mengganggu perhitungan panjang huruf
    teks_bersih = re.sub(r'[^\w\s]', '', data)
    
    # Pisahkan jadi kata-kata
    daftar_kata = teks_bersih.split()
    
    # Ambil hanya kata dengan panjang > 3 huruf
    kata_yang_disaring = [kata for kata in daftar_kata if len(kata) > 3]
    
    # Gabungkan kembali jadi kalimat
    return ' '.join(kata_yang_disaring)

# --- 2. Proses DataFrame ---
try:
    # Path file input
    path_input = os.path.join('DatasetPreprocessShopeepay','Tahap2HapusDuplikat.csv')
    data = pd.read_csv(path_input)
    
    print("File CSV berhasil dibaca. Berikut 5 baris pertama data asli:")
    print(data.head())
    print("-" * 50)
    
    # Ganti dengan nama kolom data kamu
    nama_kolom_asli = 'Review text'
    
    # Terapkan fungsi pembersihan
    data['teks_bersih'] = data[nama_kolom_asli].apply(hapus_kata_pendek)
    
    print("Fungsi berhasil diterapkan. Berikut hasilnya:")
    print(data[[nama_kolom_asli, 'teks_bersih']].head())
    print("-" * 50)
    
    # Simpan hasilnya ke file baru
    folder_tujuan = 'DatasetPreprocessShopeepay'
    nama_file_output = 'Tahap3HapusKurang3Huruf.csv'
    path_output = os.path.join(folder_tujuan, nama_file_output)
    
    data.to_csv(path_output, index=False, encoding='utf-8')
    
    print(f"DataFrame yang sudah bersih berhasil disimpan di: '{path_output}'")

except FileNotFoundError:
    print("Error: File tidak ditemukan. Mohon periksa kembali path file input Anda.")

File CSV berhasil dibaca. Berikut 5 baris pertama data asli:
                                         Review text
0  Di coba dulu. Kalau memuaskan, bisa diberikan ...
1                                       mantap murah
2                                            mantabb
3                  bisa bayar pulsa dan juga belanja
4                kenapa pas transaksi gagal mulu min
--------------------------------------------------
Fungsi berhasil diterapkan. Berikut hasilnya:
                                         Review text  \
0  Di coba dulu. Kalau memuaskan, bisa diberikan ...
1                                       mantap murah
2                                            mantabb
3                  bisa bayar pulsa dan juga belanja
4                kenapa pas transaksi gagal mulu min

                                        teks_bersih
0  coba dulu Kalau memuaskan bisa diberikan bintang
1                                      mantap murah
2                                           mantabb
3                     bisa bayar pulsa juga belanja
4                       kenapa transaksi gagal mulu
--------------------------------------------------
DataFrame yang sudah bersih berhasil disimpan di: 'DatasetPreprocessShopeepay\Tahap3HapusKurang3Huruf.csv'

Ada beberapa tahapan pra pemrosesn yang saya lakukan, tetapi karena kolom yang akan saya pakai hanya kolom isi ulasan X saja atau kolom yang bernama "full_text" maka saya akan menyimpan kolom tersebut kedalam satu file terlebih dahulu agar meringankan beban komputasi data.Setelah dilakukan penghapusan kata kurang dari 3 huruf didapatkan kolom baru yaitu kolom "teks_bersih", selanjutnya adalah proses preprocessing. Beberapa tahapan yang saya lakukan sebagai berikut:

## 1. Casefolding
casefolding data atau biasa disebut dengan pembersihan data seprti menyamakan hurup menjadi huruf kecil semua, menghapus karakter khusus seperti ?!@#$, dan menghapus angka.

In [6]:
import re
import pandas as pd
import nltk
from nltk.corpus import stopwords
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory


#1. Casefolding data
def caseFolding(data, text_field, new_text_field_name):
    # Mengubah huruf kapital menjadi kecil
    data[new_text_field_name] = data[text_field].str.lower()
    # Menghapus karakter seperti @, #
    data[new_text_field_name] = data[new_text_field_name].apply(lambda elem: re.sub(r"(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)|^rt|http.+?", "", elem))
    # Menghapus angka
    data[new_text_field_name] = data[new_text_field_name].apply(lambda elem: re.sub(r"\d+", "", elem))
    return data

data_clean = caseFolding(data, 'teks_bersih', 'clean_text')
data_clean.head(10)

,Review text,teks_bersih,clean_text
0,"Di coba dulu. Kalau memuaskan, bisa diberikan ...",coba dulu Kalau memuaskan bisa diberikan bintang,coba dulu kalau memuaskan bisa diberikan bintang
1,mantap murah,mantap murah,mantap murah
2,mantabb,mantabb,mantabb
3,bisa bayar pulsa dan juga belanja,bisa bayar pulsa juga belanja,bisa bayar pulsa juga belanja
4,kenapa pas transaksi gagal mulu min,kenapa transaksi gagal mulu,kenapa transaksi gagal mulu
5,gabisa klaim dm epep👎,gabisa klaim epep,gabisa klaim epep
6,aplikasi apa ini. saya transfer ke dana tpi ti...,aplikasi saya transfer dana tidak msuk2 saldo ...,aplikasi saya transfer dana tidak msuk saldo s...
7,😘,,
8,lama banget kalo girim uang 1 hari apapaan ora...,lama banget kalo girim uang hari apapaan orang...,lama banget kalo girim uang hari apapaan orang...
9,aplikasinya bagus,aplikasinya bagus,aplikasinya bagus

## 2. Normalisasi Teks

In [7]:
# 2. Normalisasi kata tidak baku
def replace_taboo_words(text, kamus_tidak_baku):
    if isinstance(text, str):
        words = text.split()
        replaced_words = []
        kalimat_baku = []
        kata_diganti = []
        kata_tidak_baku_hash = []

        for word in words:
            if word in kamus_tidak_baku:
                baku_word = kamus_tidak_baku[word]
                if isinstance(baku_word, str) and all(char.isalpha() or char.isspace() for char in baku_word):
                    replaced_words.append(baku_word)
                    kalimat_baku.append(baku_word)
                    kata_diganti.append(word)
                    kata_tidak_baku_hash.append(hash(word))
                else:
                    replaced_words.append(word)
            else:
                replaced_words.append(word)

        replaced_text = ' '.join(replaced_words)
        return replaced_text, kalimat_baku, kata_diganti, kata_tidak_baku_hash
    else:
        return "", [], [], []

# Load kamus data
kamus_data = pd.read_excel("../../kamus/kamuskatabaku.xlsx")
kamus_tidak_baku = dict(zip(kamus_data["tidak_baku"], kamus_data["kata_baku"]))
results = data["clean_text"].apply(lambda x: replace_taboo_words(x, kamus_tidak_baku))
data["normalisasi_text"], data["kata_baku"], data["kata_tidak_baku"], data["kata_tidak_baku_Hash"] = zip(*results)
data[['Review text', 'teks_bersih', 'clean_text', 'normalisasi_text']].head(10)

,Review text,teks_bersih,clean_text,normalisasi_text
0,"Di coba dulu. Kalau memuaskan, bisa diberikan ...",coba dulu Kalau memuaskan bisa diberikan bintang,coba dulu kalau memuaskan bisa diberikan bintang,coba dulu kalau memuaskan bisa diberikan bintang
1,mantap murah,mantap murah,mantap murah,mantap murah
2,mantabb,mantabb,mantabb,mantab
3,bisa bayar pulsa dan juga belanja,bisa bayar pulsa juga belanja,bisa bayar pulsa juga belanja,bisa bayar pulsa juga belanja
4,kenapa pas transaksi gagal mulu min,kenapa transaksi gagal mulu,kenapa transaksi gagal mulu,kenapa transaksi gagal mulu
5,gabisa klaim dm epep👎,gabisa klaim epep,gabisa klaim epep,tidak bisa klaim epep
6,aplikasi apa ini. saya transfer ke dana tpi ti...,aplikasi saya transfer dana tidak msuk2 saldo ...,aplikasi saya transfer dana tidak msuk saldo s...,aplikasi saya transfer dana tidak masuk saldo ...
7,😘,,,
8,lama banget kalo girim uang 1 hari apapaan ora...,lama banget kalo girim uang hari apapaan orang...,lama banget kalo girim uang hari apapaan orang...,lama banget kalau girim uang hari apapaan oran...
9,aplikasinya bagus,aplikasinya bagus,aplikasinya bagus,aplikasinya bagus

## 3. Tokenizing

In [8]:
# 3. tokenizing (memisahkan teks menjadi potongan potongan)

def tokenize(text):
    tokens = text.split()
    return tokens

data["tokenize"] = data["normalisasi_text"].apply(tokenize)
data.head(10)

,Review text,teks_bersih,clean_text,normalisasi_text,kata_baku,kata_tidak_baku,kata_tidak_baku_Hash,tokenize
0,"Di coba dulu. Kalau memuaskan, bisa diberikan ...",coba dulu Kalau memuaskan bisa diberikan bintang,coba dulu kalau memuaskan bisa diberikan bintang,coba dulu kalau memuaskan bisa diberikan bintang,[],[],[],"[coba, dulu, kalau, memuaskan, bisa, diberikan..."
1,mantap murah,mantap murah,mantap murah,mantap murah,[],[],[],"[mantap, murah]"
2,mantabb,mantabb,mantabb,mantab,[mantab],[mantabb],[-3828582975805372089],[mantab]
3,bisa bayar pulsa dan juga belanja,bisa bayar pulsa juga belanja,bisa bayar pulsa juga belanja,bisa bayar pulsa juga belanja,[],[],[],"[bisa, bayar, pulsa, juga, belanja]"
4,kenapa pas transaksi gagal mulu min,kenapa transaksi gagal mulu,kenapa transaksi gagal mulu,kenapa transaksi gagal mulu,[],[],[],"[kenapa, transaksi, gagal, mulu]"
5,gabisa klaim dm epep👎,gabisa klaim epep,gabisa klaim epep,tidak bisa klaim epep,[tidak bisa],[gabisa],[227772446771717277],"[tidak, bisa, klaim, epep]"
6,aplikasi apa ini. saya transfer ke dana tpi ti...,aplikasi saya transfer dana tidak msuk2 saldo ...,aplikasi saya transfer dana tidak msuk saldo s...,aplikasi saya transfer dana tidak masuk saldo ...,[masuk],[msuk],[-7513718147365167009],"[aplikasi, saya, transfer, dana, tidak, masuk,..."
7,😘,,,,[],[],[],[]
8,lama banget kalo girim uang 1 hari apapaan ora...,lama banget kalo girim uang hari apapaan orang...,lama banget kalo girim uang hari apapaan orang...,lama banget kalau girim uang hari apapaan oran...,"[kalau, meminta]","[kalo, minta]","[-5168973734848169673, -8470746675556570357]","[lama, banget, kalau, girim, uang, hari, apapa..."
9,aplikasinya bagus,aplikasinya bagus,aplikasinya bagus,aplikasinya bagus,[],[],[],"[aplikasinya, bagus]"

## 4. Stopword Removal

In [9]:
#  4. Stopword removal (menghapus kata umum atau sambung contoh yang, di, dan)

# Unduh stopwords bahasa Indonesia
nltk.download('stopwords')

# Mendapatkan stopwords bahasa Indonesia
stop_words = stopwords.words('indonesian')
def remove_stopwords(text):
    return [word for word in text if word not in stop_words]

data['stopword_removal'] = data['tokenize'].apply(lambda x: remove_stopwords(x))
data.head(10)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,Review text,teks_bersih,clean_text,normalisasi_text,kata_baku,kata_tidak_baku,kata_tidak_baku_Hash,tokenize,stopword_removal
0,"Di coba dulu. Kalau memuaskan, bisa diberikan ...",coba dulu Kalau memuaskan bisa diberikan bintang,coba dulu kalau memuaskan bisa diberikan bintang,coba dulu kalau memuaskan bisa diberikan bintang,[],[],[],"[coba, dulu, kalau, memuaskan, bisa, diberikan...","[coba, memuaskan, bintang]"
1,mantap murah,mantap murah,mantap murah,mantap murah,[],[],[],"[mantap, murah]","[mantap, murah]"
2,mantabb,mantabb,mantabb,mantab,[mantab],[mantabb],[-3828582975805372089],[mantab],[mantab]
3,bisa bayar pulsa dan juga belanja,bisa bayar pulsa juga belanja,bisa bayar pulsa juga belanja,bisa bayar pulsa juga belanja,[],[],[],"[bisa, bayar, pulsa, juga, belanja]","[bayar, pulsa, belanja]"
4,kenapa pas transaksi gagal mulu min,kenapa transaksi gagal mulu,kenapa transaksi gagal mulu,kenapa transaksi gagal mulu,[],[],[],"[kenapa, transaksi, gagal, mulu]","[transaksi, gagal, mulu]"
5,gabisa klaim dm epep👎,gabisa klaim epep,gabisa klaim epep,tidak bisa klaim epep,[tidak bisa],[gabisa],[227772446771717277],"[tidak, bisa, klaim, epep]","[klaim, epep]"
6,aplikasi apa ini. saya transfer ke dana tpi ti...,aplikasi saya transfer dana tidak msuk2 saldo ...,aplikasi saya transfer dana tidak msuk saldo s...,aplikasi saya transfer dana tidak masuk saldo ...,[masuk],[msuk],[-7513718147365167009],"[aplikasi, saya, transfer, dana, tidak, masuk,...","[aplikasi, transfer, dana, masuk, saldo, menge..."
7,😘,,,,[],[],[],[],[]
8,lama banget kalo girim uang 1 hari apapaan ora...,lama banget kalo girim uang hari apapaan orang...,lama banget kalo girim uang hari apapaan orang...,lama banget kalau girim uang hari apapaan oran...,"[kalau, meminta]","[kalo, minta]","[-5168973734848169673, -8470746675556570357]","[lama, banget, kalau, girim, uang, hari, apapa...","[banget, girim, uang, apapaan, orang, butuh, g..."
9,aplikasinya bagus,aplikasinya bagus,aplikasinya bagus,aplikasinya bagus,[],[],[],"[aplikasinya, bagus]","[aplikasinya, bagus]"

## 5. Steming

In [10]:
 # Step 5: Stemming

factory = StemmerFactory()
stemmer = factory.create_stemmer()

def stem_text(text):
    return [stemmer.stem(word) for word in text]

data['steming_data'] = data['stopword_removal'].apply(lambda x:' '.join(stem_text(x)))
data.head(10)

,Review text,teks_bersih,clean_text,normalisasi_text,kata_baku,kata_tidak_baku,kata_tidak_baku_Hash,tokenize,stopword_removal,steming_data
0,"Di coba dulu. Kalau memuaskan, bisa diberikan ...",coba dulu Kalau memuaskan bisa diberikan bintang,coba dulu kalau memuaskan bisa diberikan bintang,coba dulu kalau memuaskan bisa diberikan bintang,[],[],[],"[coba, dulu, kalau, memuaskan, bisa, diberikan...","[coba, memuaskan, bintang]",coba muas bintang
1,mantap murah,mantap murah,mantap murah,mantap murah,[],[],[],"[mantap, murah]","[mantap, murah]",mantap murah
2,mantabb,mantabb,mantabb,mantab,[mantab],[mantabb],[-3828582975805372089],[mantab],[mantab],mantab
3,bisa bayar pulsa dan juga belanja,bisa bayar pulsa juga belanja,bisa bayar pulsa juga belanja,bisa bayar pulsa juga belanja,[],[],[],"[bisa, bayar, pulsa, juga, belanja]","[bayar, pulsa, belanja]",bayar pulsa belanja
4,kenapa pas transaksi gagal mulu min,kenapa transaksi gagal mulu,kenapa transaksi gagal mulu,kenapa transaksi gagal mulu,[],[],[],"[kenapa, transaksi, gagal, mulu]","[transaksi, gagal, mulu]",transaksi gagal mulu
5,gabisa klaim dm epep👎,gabisa klaim epep,gabisa klaim epep,tidak bisa klaim epep,[tidak bisa],[gabisa],[227772446771717277],"[tidak, bisa, klaim, epep]","[klaim, epep]",klaim epep
6,aplikasi apa ini. saya transfer ke dana tpi ti...,aplikasi saya transfer dana tidak msuk2 saldo ...,aplikasi saya transfer dana tidak msuk saldo s...,aplikasi saya transfer dana tidak masuk saldo ...,[masuk],[msuk],[-7513718147365167009],"[aplikasi, saya, transfer, dana, tidak, masuk,...","[aplikasi, transfer, dana, masuk, saldo, menge...",aplikasi transfer dana masuk saldo kecewa
7,😘,,,,[],[],[],[],[],
8,lama banget kalo girim uang 1 hari apapaan ora...,lama banget kalo girim uang hari apapaan orang...,lama banget kalo girim uang hari apapaan orang...,lama banget kalau girim uang hari apapaan oran...,"[kalau, meminta]","[kalo, minta]","[-5168973734848169673, -8470746675556570357]","[lama, banget, kalau, girim, uang, hari, apapa...","[banget, girim, uang, apapaan, orang, butuh, g...",banget girim uang apapaan orang butuh gilir saldo
9,aplikasinya bagus,aplikasinya bagus,aplikasinya bagus,aplikasinya bagus,[],[],[],"[aplikasinya, bagus]","[aplikasinya, bagus]",aplikasi bagus

Cek missing value setelah dilakukan semua tahapan preprocessing

In [11]:
data.isnull().sum()

Review text             0
teks_bersih             0
clean_text              0
normalisasi_text        0
kata_baku               0
kata_tidak_baku         0
kata_tidak_baku_Hash    0
tokenize                0
stopword_removal        0
steming_data            0
dtype: int64

In [12]:
import pandas as pd

data = pd.DataFrame(data[["Review text","clean_text","normalisasi_text","tokenize","stopword_removal","steming_data"]])
data.head(10)

,Review text,clean_text,normalisasi_text,tokenize,stopword_removal,steming_data
0,"Di coba dulu. Kalau memuaskan, bisa diberikan ...",coba dulu kalau memuaskan bisa diberikan bintang,coba dulu kalau memuaskan bisa diberikan bintang,"[coba, dulu, kalau, memuaskan, bisa, diberikan...","[coba, memuaskan, bintang]",coba muas bintang
1,mantap murah,mantap murah,mantap murah,"[mantap, murah]","[mantap, murah]",mantap murah
2,mantabb,mantabb,mantab,[mantab],[mantab],mantab
3,bisa bayar pulsa dan juga belanja,bisa bayar pulsa juga belanja,bisa bayar pulsa juga belanja,"[bisa, bayar, pulsa, juga, belanja]","[bayar, pulsa, belanja]",bayar pulsa belanja
4,kenapa pas transaksi gagal mulu min,kenapa transaksi gagal mulu,kenapa transaksi gagal mulu,"[kenapa, transaksi, gagal, mulu]","[transaksi, gagal, mulu]",transaksi gagal mulu
5,gabisa klaim dm epep👎,gabisa klaim epep,tidak bisa klaim epep,"[tidak, bisa, klaim, epep]","[klaim, epep]",klaim epep
6,aplikasi apa ini. saya transfer ke dana tpi ti...,aplikasi saya transfer dana tidak msuk saldo s...,aplikasi saya transfer dana tidak masuk saldo ...,"[aplikasi, saya, transfer, dana, tidak, masuk,...","[aplikasi, transfer, dana, masuk, saldo, menge...",aplikasi transfer dana masuk saldo kecewa
7,😘,,,[],[],
8,lama banget kalo girim uang 1 hari apapaan ora...,lama banget kalo girim uang hari apapaan orang...,lama banget kalau girim uang hari apapaan oran...,"[lama, banget, kalau, girim, uang, hari, apapa...","[banget, girim, uang, apapaan, orang, butuh, g...",banget girim uang apapaan orang butuh gilir saldo
9,aplikasinya bagus,aplikasinya bagus,aplikasinya bagus,"[aplikasinya, bagus]","[aplikasinya, bagus]",aplikasi bagus

Karena setelah dilakukan preprocessing terdapat string yang didalamnya kosong atau tidak berisi data maka dilakukan penghapusan

In [16]:
# jumlah data sebelum
before = len(data)

# hapus teks kosong
data = data[data["steming_data"].str.strip() != ""]

# jumlah data sesudah
after = len(data)

print(f"Jumlah data sebelum dihapus : {before}")
print(f"Jumlah data sesudah dihapus : {after}")
print(f"Jumlah data terhapus        : {before - after}")

Jumlah data sebelum dihapus : 8877
Jumlah data sesudah dihapus : 8877
Jumlah data terhapus        : 0

In [15]:
folder_tujuan = 'DatasetPreprocessShopeepay' 

if not os.path.exists(folder_tujuan):
    os.makedirs(folder_tujuan)

path_output = os.path.join(folder_tujuan, 'Tahap4Preprocessing.csv')
data.to_csv(path_output, index=False, encoding='utf-8')
print(f"File berhasil disimpan di: {path_output}")
data.info()

File berhasil disimpan di: DatasetPreprocessShopeepay\Tahap4Preprocessing.csv
<class 'pandas.core.frame.DataFrame'>
Index: 8877 entries, 0 to 9158
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Review text       8877 non-null   object
 1   clean_text        8877 non-null   object
 2   normalisasi_text  8877 non-null   object
 3   tokenize          8877 non-null   object
 4   stopword_removal  8877 non-null   object
 5   steming_data      8877 non-null   object
dtypes: object(6)
memory usage: 485.5+ KB