Karena yang akan digunakan hanya kolom review text atau isi ulasan maka disimpan file csv dengan isi kolom review text untuk meringankan beban komputasi

In [1]:
import os
import pandas as pd

# Membaca file dan menampilkan 5 data pertama
df = pd.read_csv("../../ScrapingData/hasilScrapUlasanAplikasiDana.csv")
print(df.head())

                              Review id         Username  Rating  \
0  eb54a202-65d5-497f-bcd5-2aaef78905ae  Pengguna Google       5
1  acacd759-d766-48bc-95a4-ec5e7e54443b  Pengguna Google       5
2  0d6208ff-16a0-40fe-8568-6bf8cc8d5ef6  Pengguna Google       5
3  d1e8c879-6f6d-4a0d-bead-d41b6838c4de  Pengguna Google       4
4  5fa08dbd-8ed2-4155-aa8e-1eb59eb2e181  Pengguna Google       4

                                         Review text                 Date
0                                       keren sekali  2025-12-30 21:04:51
1  fitur dana cicil tidak bisa di akses padahal s...  2025-12-30 21:04:47
2                                        sangat baik  2025-12-30 21:04:10
3  saya sempet kesel waktu itu, jadi saya beli pa...  2025-12-30 21:03:43
4                            Belum menerima hasil,..  2025-12-30 21:03:14

In [2]:
df = df[["Review text"]]
print(df.tail())

                                             Review text
14995                                   aplikasi thebest
14996                            apk yg paling bagus 🥰🥰🥰
14997                                              bagus
14998    Dana instant kok gak muncul. di tmn aku muncul.
14999  semakin membagongkan apk dana ini, beli data s...

In [3]:
# Tentukan path folder tujuan
folder_tujuan = 'DatasetPreprocessDana' 

# Pastikan folder tujuan sudah ada, jika belum maka buat folder tersebut
# Ini adalah langkah yang baik untuk menghindari error
if not os.path.exists(folder_tujuan):
    os.makedirs(folder_tujuan)

# Gabungkan path folder dengan nama file yang diinginkan
path_output = os.path.join(folder_tujuan, 'Tahap1IsiUlasan.csv')

# Simpan DataFrame ke path yang sudah ditentukan
df.to_csv(path_output, index=False, encoding='utf-8')

print(f"File berhasil disimpan di: {path_output}")

# Tetap tampilkan info DataFrame setelah menyimpan
df.info()

File berhasil disimpan di: DatasetPreprocessDana\Tahap1IsiUlasan.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Review text  15000 non-null  object
dtypes: object(1)
memory usage: 117.3+ KB

## Hapus data duplikat dan data kurang dari 3 huruf

Data kurang dari 3 huruf dihapus karena data kurang dari 3 huruf seringkali tidak mengandung isi sentimen. Setelah dilakukan penghapusan data kurang dari 3 huruf, selanjutnya akan muncul kolom baru yaitu kolom teks_bersih yang berisi data setelah dilakukan penghapusan.

In [4]:
import pandas as pd
import os

# --- PENGOLAHAN FILE ---

# 1. Tentukan nama file CSV yang akan diproses
nama_file_input = 'DatasetPreprocessDana/Tahap1IsiUlasan.csv' # GANTI DENGAN NAMA FILE ANDA

# Pastikan file ada sebelum melanjutkan
if not os.path.exists(nama_file_input):
    print(f"Error: File tidak ditemukan di '{os.path.abspath(nama_file_input)}'")
else:
    # 2. Langsung baca satu file CSV ke dalam DataFrame
    print(f"Membaca file: '{nama_file_input}'")
    data = pd.read_csv(nama_file_input)

    print(f"\nJumlah baris sebelum menghapus duplikat: {len(data)}")

    # 3. Hapus baris duplikat berdasarkan kolom 'full_text'
    data.drop_duplicates(subset=['Review text'], inplace=True, keep='first')

    print(f"Jumlah baris setelah menghapus duplikat: {len(data)}")

    # --- PENYIMPANAN FILE ---

    # 4. Tentukan nama folder dan file output
    folder_tujuan = 'DatasetPreprocessDana'
    
    # Tentukan path lengkap untuk file output
    nama_file_output = 'Tahap2HapusDuplikat.csv'
    path_output = os.path.join(folder_tujuan, nama_file_output)

    # 5. Simpan DataFrame yang sudah bersih ke file baru
    data.to_csv(path_output, index=False, encoding='utf-8')

    print(f"\nSukses! Duplikat telah dihapus dan file disimpan di:")
    print(f"'{path_output}'")

Membaca file: 'DatasetPreprocessDana/Tahap1IsiUlasan.csv'

Jumlah baris sebelum menghapus duplikat: 15000
Jumlah baris setelah menghapus duplikat: 10151

Sukses! Duplikat telah dihapus dan file disimpan di:
'DatasetPreprocessDana\Tahap2HapusDuplikat.csv'

In [ ]:
import pandas as pd
import re
import os

# 1. Fungsi untuk menghapus kata dengan huruf <= 3
def hapus_kata_pendek(data):
    if not isinstance(data, str):
        return ''
    
    # Hapus tanda baca supaya tidak mengganggu perhitungan panjang huruf
    teks_bersih = re.sub(r'[^\w\s]', '', data)
    
    # Pisahkan jadi kata-kata
    daftar_kata = teks_bersih.split()
    
    # Ambil hanya kata dengan panjang > 3 huruf
    kata_yang_disaring = [kata for kata in daftar_kata if len(kata) > 3]
    
    # Gabungkan kembali jadi kalimat
    return ' '.join(kata_yang_disaring)

# --- 2. Proses DataFrame ---
try:
    # Path file input
    path_input = os.path.join('DatasetPreprocessDana','Tahap2HapusDuplikat.csv')
    data = pd.read_csv(path_input)
    
    print("File CSV berhasil dibaca. Berikut 5 baris pertama data asli:")
    print(data.head())
    print("-" * 50)
    
    # Ganti dengan nama kolom data kamu
    nama_kolom_asli = 'Review text'
    
    # Terapkan fungsi pembersihan
    data['teks_bersih'] = data[nama_kolom_asli].apply(hapus_kata_pendek)
    
    print("Fungsi berhasil diterapkan. Berikut hasilnya:")
    print(data[[nama_kolom_asli, 'teks_bersih']].head())
    print("-" * 50)
    
    # Simpan hasilnya ke file baru
    folder_tujuan = 'DatasetPreprocessDana'
    nama_file_output = 'Tahap3HapusKurang3Huruf.csv'
    path_output = os.path.join(folder_tujuan, nama_file_output)
    
    data.to_csv(path_output, index=False, encoding='utf-8')
    
    print(f"DataFrame yang sudah bersih berhasil disimpan di: '{path_output}'")

except FileNotFoundError:
    print("Error: File tidak ditemukan. Mohon periksa kembali path file input Anda.")

File CSV berhasil dibaca. Berikut 5 baris pertama data asli:
                                         Review text
0                                       keren sekali
1  fitur dana cicil tidak bisa di akses padahal s...
2                                        sangat baik
3  saya sempet kesel waktu itu, jadi saya beli pa...
4                            Belum menerima hasil,..
--------------------------------------------------
Fungsi berhasil diterapkan. Berikut hasilnya:
                                         Review text  \
0                                       keren sekali
1  fitur dana cicil tidak bisa di akses padahal s...
2                                        sangat baik
3  saya sempet kesel waktu itu, jadi saya beli pa...
4                            Belum menerima hasil,..

                                         teks_bersih
0                                       keren sekali
1  fitur dana cicil tidak bisa akses padahal syar...
2                                        sangat baik
3  saya sempet kesel waktu jadi saya beli paketan...
4                               Belum menerima hasil
--------------------------------------------------
DataFrame yang sudah bersih berhasil disimpan di: 'DatasetPreprocessDana\Tahap3HapusKurang3Huruf.csv'

Ada beberapa tahapan pra pemrosesn yang saya lakukan, tetapi karena kolom yang akan saya pakai hanya kolom isi ulasan X saja atau kolom yang bernama "review_text" maka saya akan menyimpan kolom tersebut kedalam satu file terlebih dahulu agar meringankan beban komputasi data.Setelah dilakukan penghapusan kata kurang dari 3 huruf didapatkan kolom baru yaitu kolom "teks_bersih", selanjutnya adalah proses preprocessing. Beberapa tahapan yang saya lakukan sebagai berikut:

## 1. Casefolding
casefolding data atau biasa disebut dengan pembersihan data seprti menyamakan hurup menjadi huruf kecil semua, menghapus karakter khusus seperti ?!@#$, dan menghapus angka.

In [6]:
import re
import pandas as pd
import nltk
from nltk.corpus import stopwords
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory


#1. Casefolding data
def caseFolding(data, text_field, new_text_field_name):
    # Mengubah huruf kapital menjadi kecil
    data[new_text_field_name] = data[text_field].str.lower()
    # Menghapus karakter seperti @, #
    data[new_text_field_name] = data[new_text_field_name].apply(lambda elem: re.sub(r"(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)|^rt|http.+?", "", elem))
    # Menghapus angka
    data[new_text_field_name] = data[new_text_field_name].apply(lambda elem: re.sub(r"\d+", "", elem))
    return data

data_clean = caseFolding(data, 'teks_bersih', 'clean_text')
data_clean.head(10)

,Review text,teks_bersih,clean_text
0,keren sekali,keren sekali,keren sekali
1,fitur dana cicil tidak bisa di akses padahal s...,fitur dana cicil tidak bisa akses padahal syar...,fitur dana cicil tidak bisa akses padahal syar...
2,sangat baik,sangat baik,sangat baik
3,"saya sempet kesel waktu itu, jadi saya beli pa...",saya sempet kesel waktu jadi saya beli paketan...,saya sempet kesel waktu jadi saya beli paketan...
4,"Belum menerima hasil,..",Belum menerima hasil,belum menerima hasil
5,membantu sekali.tks,membantu sekalitks,membantu sekalitks
6,Beli paket kuota di Myim3 bayarnya pakai qris ...,Beli paket kuota Myim3 bayarnya pakai qris Dan...,beli paket kuota myim bayarnya pakai qris dana...
7,semoga dana tetap menjaga ke amanan pengguna n...,semoga dana tetap menjaga amanan pengguna teri...,semoga dana tetap menjaga amanan pengguna teri...
8,"sangat bagus kakak, sangat membantu sekali",sangat bagus kakak sangat membantu sekali,sangat bagus kakak sangat membantu sekali
9,terimakasih aplikasi ini sangat membatu kita s...,terimakasih aplikasi sangat membatu kita semuanya,terimakasih aplikasi sangat membatu kita semuanya

## 2. Normalisasi Teks

In [7]:
# 2. Normalisasi kata tidak baku
def replace_taboo_words(text, kamus_tidak_baku):
    if isinstance(text, str):
        words = text.split()
        replaced_words = []
        kalimat_baku = []
        kata_diganti = []
        kata_tidak_baku_hash = []

        for word in words:
            if word in kamus_tidak_baku:
                baku_word = kamus_tidak_baku[word]
                if isinstance(baku_word, str) and all(char.isalpha() or char.isspace() for char in baku_word):
                    replaced_words.append(baku_word)
                    kalimat_baku.append(baku_word)
                    kata_diganti.append(word)
                    kata_tidak_baku_hash.append(hash(word))
                else:
                    replaced_words.append(word)
            else:
                replaced_words.append(word)

        replaced_text = ' '.join(replaced_words)
        return replaced_text, kalimat_baku, kata_diganti, kata_tidak_baku_hash
    else:
        return "", [], [], []

# Load kamus data
kamus_data = pd.read_excel("../../kamus/kamuskatabaku.xlsx")
kamus_tidak_baku = dict(zip(kamus_data["tidak_baku"], kamus_data["kata_baku"]))
results = data["clean_text"].apply(lambda x: replace_taboo_words(x, kamus_tidak_baku))
data["normalisasi_text"], data["kata_baku"], data["kata_tidak_baku"], data["kata_tidak_baku_Hash"] = zip(*results)
data[['Review text', 'teks_bersih', 'clean_text', 'normalisasi_text']].head(10)

,Review text,teks_bersih,clean_text,normalisasi_text
0,keren sekali,keren sekali,keren sekali,keren sekali
1,fitur dana cicil tidak bisa di akses padahal s...,fitur dana cicil tidak bisa akses padahal syar...,fitur dana cicil tidak bisa akses padahal syar...,fitur dana cicil tidak bisa akses padahal syar...
2,sangat baik,sangat baik,sangat baik,sangat baik
3,"saya sempet kesel waktu itu, jadi saya beli pa...",saya sempet kesel waktu jadi saya beli paketan...,saya sempet kesel waktu jadi saya beli paketan...,saya sempat kesel waktu jadi saya beli paketan...
4,"Belum menerima hasil,..",Belum menerima hasil,belum menerima hasil,belum menerima hasil
5,membantu sekali.tks,membantu sekalitks,membantu sekalitks,membantu sekalitks
6,Beli paket kuota di Myim3 bayarnya pakai qris ...,Beli paket kuota Myim3 bayarnya pakai qris Dan...,beli paket kuota myim bayarnya pakai qris dana...,beli paket kuota myim bayarnya pakai qris dana...
7,semoga dana tetap menjaga ke amanan pengguna n...,semoga dana tetap menjaga amanan pengguna teri...,semoga dana tetap menjaga amanan pengguna teri...,semoga dana tetap menjaga amanan pengguna teri...
8,"sangat bagus kakak, sangat membantu sekali",sangat bagus kakak sangat membantu sekali,sangat bagus kakak sangat membantu sekali,sangat bagus kakak sangat membantu sekali
9,terimakasih aplikasi ini sangat membatu kita s...,terimakasih aplikasi sangat membatu kita semuanya,terimakasih aplikasi sangat membatu kita semuanya,terimakasih aplikasi sangat membatu kita semuanya

## 3. Tokenizing

In [8]:
# 3. tokenizing (memisahkan teks menjadi potongan potongan)

def tokenize(text):
    tokens = text.split()
    return tokens

data["tokenize"] = data["normalisasi_text"].apply(tokenize)
data.head(10)

,Review text,teks_bersih,clean_text,normalisasi_text,kata_baku,kata_tidak_baku,kata_tidak_baku_Hash,tokenize
0,keren sekali,keren sekali,keren sekali,keren sekali,[],[],[],"[keren, sekali]"
1,fitur dana cicil tidak bisa di akses padahal s...,fitur dana cicil tidak bisa akses padahal syar...,fitur dana cicil tidak bisa akses padahal syar...,fitur dana cicil tidak bisa akses padahal syar...,[],[],[],"[fitur, dana, cicil, tidak, bisa, akses, padah..."
2,sangat baik,sangat baik,sangat baik,sangat baik,[],[],[],"[sangat, baik]"
3,"saya sempet kesel waktu itu, jadi saya beli pa...",saya sempet kesel waktu jadi saya beli paketan...,saya sempet kesel waktu jadi saya beli paketan...,saya sempat kesel waktu jadi saya beli paketan...,"[sempat, pakai, tetap, pakai, sudah]","[sempet, pake, tetep, pake, udah]","[1208639474208417770, -5653464460069155318, -1...","[saya, sempat, kesel, waktu, jadi, saya, beli,..."
4,"Belum menerima hasil,..",Belum menerima hasil,belum menerima hasil,belum menerima hasil,[],[],[],"[belum, menerima, hasil]"
5,membantu sekali.tks,membantu sekalitks,membantu sekalitks,membantu sekalitks,[],[],[],"[membantu, sekalitks]"
6,Beli paket kuota di Myim3 bayarnya pakai qris ...,Beli paket kuota Myim3 bayarnya pakai qris Dan...,beli paket kuota myim bayarnya pakai qris dana...,beli paket kuota myim bayarnya pakai qris dana...,"[sampai, sampai, pakai, beberapa]","[sampe, sampe, pake, bbrpa]","[6807555544250441633, 6807555544250441633, -56...","[beli, paket, kuota, myim, bayarnya, pakai, qr..."
7,semoga dana tetap menjaga ke amanan pengguna n...,semoga dana tetap menjaga amanan pengguna teri...,semoga dana tetap menjaga amanan pengguna teri...,semoga dana tetap menjaga amanan pengguna teri...,[],[],[],"[semoga, dana, tetap, menjaga, amanan, penggun..."
8,"sangat bagus kakak, sangat membantu sekali",sangat bagus kakak sangat membantu sekali,sangat bagus kakak sangat membantu sekali,sangat bagus kakak sangat membantu sekali,[],[],[],"[sangat, bagus, kakak, sangat, membantu, sekali]"
9,terimakasih aplikasi ini sangat membatu kita s...,terimakasih aplikasi sangat membatu kita semuanya,terimakasih aplikasi sangat membatu kita semuanya,terimakasih aplikasi sangat membatu kita semuanya,[],[],[],"[terimakasih, aplikasi, sangat, membatu, kita,..."

## 4. Stopword Removal

In [9]:
#  4. Stopword removal (menghapus kata umum atau sambung contoh yang, di, dan)

# Unduh stopwords bahasa Indonesia
nltk.download('stopwords')

# Mendapatkan stopwords bahasa Indonesia
stop_words = stopwords.words('indonesian')
def remove_stopwords(text):
    return [word for word in text if word not in stop_words]

data['stopword_removal'] = data['tokenize'].apply(lambda x: remove_stopwords(x))
data.head(10)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,Review text,teks_bersih,clean_text,normalisasi_text,kata_baku,kata_tidak_baku,kata_tidak_baku_Hash,tokenize,stopword_removal
0,keren sekali,keren sekali,keren sekali,keren sekali,[],[],[],"[keren, sekali]",[keren]
1,fitur dana cicil tidak bisa di akses padahal s...,fitur dana cicil tidak bisa akses padahal syar...,fitur dana cicil tidak bisa akses padahal syar...,fitur dana cicil tidak bisa akses padahal syar...,[],[],[],"[fitur, dana, cicil, tidak, bisa, akses, padah...","[fitur, dana, cicil, akses, syarat, memenuhi]"
2,sangat baik,sangat baik,sangat baik,sangat baik,[],[],[],"[sangat, baik]",[]
3,"saya sempet kesel waktu itu, jadi saya beli pa...",saya sempet kesel waktu jadi saya beli paketan...,saya sempet kesel waktu jadi saya beli paketan...,saya sempat kesel waktu jadi saya beli paketan...,"[sempat, pakai, tetap, pakai, sudah]","[sempet, pake, tetep, pake, udah]","[1208639474208417770, -5653464460069155318, -1...","[saya, sempat, kesel, waktu, jadi, saya, beli,...","[kesel, beli, paketan, dana, kepake, nyalain, ..."
4,"Belum menerima hasil,..",Belum menerima hasil,belum menerima hasil,belum menerima hasil,[],[],[],"[belum, menerima, hasil]","[menerima, hasil]"
5,membantu sekali.tks,membantu sekalitks,membantu sekalitks,membantu sekalitks,[],[],[],"[membantu, sekalitks]","[membantu, sekalitks]"
6,Beli paket kuota di Myim3 bayarnya pakai qris ...,Beli paket kuota Myim3 bayarnya pakai qris Dan...,beli paket kuota myim bayarnya pakai qris dana...,beli paket kuota myim bayarnya pakai qris dana...,"[sampai, sampai, pakai, beberapa]","[sampe, sampe, pake, bbrpa]","[6807555544250441633, 6807555544250441633, -56...","[beli, paket, kuota, myim, bayarnya, pakai, qr...","[beli, paket, kuota, myim, bayarnya, pakai, qr..."
7,semoga dana tetap menjaga ke amanan pengguna n...,semoga dana tetap menjaga amanan pengguna teri...,semoga dana tetap menjaga amanan pengguna teri...,semoga dana tetap menjaga amanan pengguna teri...,[],[],[],"[semoga, dana, tetap, menjaga, amanan, penggun...","[semoga, dana, menjaga, amanan, pengguna, teri..."
8,"sangat bagus kakak, sangat membantu sekali",sangat bagus kakak sangat membantu sekali,sangat bagus kakak sangat membantu sekali,sangat bagus kakak sangat membantu sekali,[],[],[],"[sangat, bagus, kakak, sangat, membantu, sekali]","[bagus, kakak, membantu]"
9,terimakasih aplikasi ini sangat membatu kita s...,terimakasih aplikasi sangat membatu kita semuanya,terimakasih aplikasi sangat membatu kita semuanya,terimakasih aplikasi sangat membatu kita semuanya,[],[],[],"[terimakasih, aplikasi, sangat, membatu, kita,...","[terimakasih, aplikasi, membatu]"

## 5. Steming

In [10]:
 # Step 5: Stemming

factory = StemmerFactory()
stemmer = factory.create_stemmer()

def stem_text(text):
    return [stemmer.stem(word) for word in text]

data['steming_data'] = data['stopword_removal'].apply(lambda x:' '.join(stem_text(x)))
data.head(10)

,Review text,teks_bersih,clean_text,normalisasi_text,kata_baku,kata_tidak_baku,kata_tidak_baku_Hash,tokenize,stopword_removal,steming_data
0,keren sekali,keren sekali,keren sekali,keren sekali,[],[],[],"[keren, sekali]",[keren],keren
1,fitur dana cicil tidak bisa di akses padahal s...,fitur dana cicil tidak bisa akses padahal syar...,fitur dana cicil tidak bisa akses padahal syar...,fitur dana cicil tidak bisa akses padahal syar...,[],[],[],"[fitur, dana, cicil, tidak, bisa, akses, padah...","[fitur, dana, cicil, akses, syarat, memenuhi]",fitur dana cicil akses syarat penuh
2,sangat baik,sangat baik,sangat baik,sangat baik,[],[],[],"[sangat, baik]",[],
3,"saya sempet kesel waktu itu, jadi saya beli pa...",saya sempet kesel waktu jadi saya beli paketan...,saya sempet kesel waktu jadi saya beli paketan...,saya sempat kesel waktu jadi saya beli paketan...,"[sempat, pakai, tetap, pakai, sudah]","[sempet, pake, tetep, pake, udah]","[1208639474208417770, -5653464460069155318, -1...","[saya, sempat, kesel, waktu, jadi, saya, beli,...","[kesel, beli, paketan, dana, kepake, nyalain, ...",kesel beli paket dana kepake nyalain duolingo ...
4,"Belum menerima hasil,..",Belum menerima hasil,belum menerima hasil,belum menerima hasil,[],[],[],"[belum, menerima, hasil]","[menerima, hasil]",terima hasil
5,membantu sekali.tks,membantu sekalitks,membantu sekalitks,membantu sekalitks,[],[],[],"[membantu, sekalitks]","[membantu, sekalitks]",bantu sekalitks
6,Beli paket kuota di Myim3 bayarnya pakai qris ...,Beli paket kuota Myim3 bayarnya pakai qris Dan...,beli paket kuota myim bayarnya pakai qris dana...,beli paket kuota myim bayarnya pakai qris dana...,"[sampai, sampai, pakai, beberapa]","[sampe, sampe, pake, bbrpa]","[6807555544250441633, 6807555544250441633, -56...","[beli, paket, kuota, myim, bayarnya, pakai, qr...","[beli, paket, kuota, myim, bayarnya, pakai, qr...",beli paket kuota myim bayar pakai qris danauan...
7,semoga dana tetap menjaga ke amanan pengguna n...,semoga dana tetap menjaga amanan pengguna teri...,semoga dana tetap menjaga amanan pengguna teri...,semoga dana tetap menjaga amanan pengguna teri...,[],[],[],"[semoga, dana, tetap, menjaga, amanan, penggun...","[semoga, dana, menjaga, amanan, pengguna, teri...",moga dana jaga aman guna terimakasih
8,"sangat bagus kakak, sangat membantu sekali",sangat bagus kakak sangat membantu sekali,sangat bagus kakak sangat membantu sekali,sangat bagus kakak sangat membantu sekali,[],[],[],"[sangat, bagus, kakak, sangat, membantu, sekali]","[bagus, kakak, membantu]",bagus kakak bantu
9,terimakasih aplikasi ini sangat membatu kita s...,terimakasih aplikasi sangat membatu kita semuanya,terimakasih aplikasi sangat membatu kita semuanya,terimakasih aplikasi sangat membatu kita semuanya,[],[],[],"[terimakasih, aplikasi, sangat, membatu, kita,...","[terimakasih, aplikasi, membatu]",terimakasih aplikasi batu

Cek missing value setelah dilakukan semua tahapan preprocessing

In [11]:
data.isnull().sum()

Review text             0
teks_bersih             0
clean_text              0
normalisasi_text        0
kata_baku               0
kata_tidak_baku         0
kata_tidak_baku_Hash    0
tokenize                0
stopword_removal        0
steming_data            0
dtype: int64

In [12]:
import pandas as pd

data = pd.DataFrame(data[["Review text","clean_text","normalisasi_text","tokenize","stopword_removal","steming_data"]])
data.head(10)

,Review text,clean_text,normalisasi_text,tokenize,stopword_removal,steming_data
0,keren sekali,keren sekali,keren sekali,"[keren, sekali]",[keren],keren
1,fitur dana cicil tidak bisa di akses padahal s...,fitur dana cicil tidak bisa akses padahal syar...,fitur dana cicil tidak bisa akses padahal syar...,"[fitur, dana, cicil, tidak, bisa, akses, padah...","[fitur, dana, cicil, akses, syarat, memenuhi]",fitur dana cicil akses syarat penuh
2,sangat baik,sangat baik,sangat baik,"[sangat, baik]",[],
3,"saya sempet kesel waktu itu, jadi saya beli pa...",saya sempet kesel waktu jadi saya beli paketan...,saya sempat kesel waktu jadi saya beli paketan...,"[saya, sempat, kesel, waktu, jadi, saya, beli,...","[kesel, beli, paketan, dana, kepake, nyalain, ...",kesel beli paket dana kepake nyalain duolingo ...
4,"Belum menerima hasil,..",belum menerima hasil,belum menerima hasil,"[belum, menerima, hasil]","[menerima, hasil]",terima hasil
5,membantu sekali.tks,membantu sekalitks,membantu sekalitks,"[membantu, sekalitks]","[membantu, sekalitks]",bantu sekalitks
6,Beli paket kuota di Myim3 bayarnya pakai qris ...,beli paket kuota myim bayarnya pakai qris dana...,beli paket kuota myim bayarnya pakai qris dana...,"[beli, paket, kuota, myim, bayarnya, pakai, qr...","[beli, paket, kuota, myim, bayarnya, pakai, qr...",beli paket kuota myim bayar pakai qris danauan...
7,semoga dana tetap menjaga ke amanan pengguna n...,semoga dana tetap menjaga amanan pengguna teri...,semoga dana tetap menjaga amanan pengguna teri...,"[semoga, dana, tetap, menjaga, amanan, penggun...","[semoga, dana, menjaga, amanan, pengguna, teri...",moga dana jaga aman guna terimakasih
8,"sangat bagus kakak, sangat membantu sekali",sangat bagus kakak sangat membantu sekali,sangat bagus kakak sangat membantu sekali,"[sangat, bagus, kakak, sangat, membantu, sekali]","[bagus, kakak, membantu]",bagus kakak bantu
9,terimakasih aplikasi ini sangat membatu kita s...,terimakasih aplikasi sangat membatu kita semuanya,terimakasih aplikasi sangat membatu kita semuanya,"[terimakasih, aplikasi, sangat, membatu, kita,...","[terimakasih, aplikasi, membatu]",terimakasih aplikasi batu

Karena setelah dilakukan preprocessing terdapat string yang didalamnya kosong atau tidak berisi data maka dilakukan penghapusan

In [17]:
# jumlah data sebelum
before = len(data)

# hapus teks kosong
data = data[data["steming_data"].str.strip() != ""]

# jumlah data sesudah
after = len(data)

print(f"Jumlah data sebelum dihapus : {before}")
print(f"Jumlah data sesudah dihapus : {after}")
print(f"Jumlah data terhapus        : {before - after}")

Jumlah data sebelum dihapus : 9883
Jumlah data sesudah dihapus : 9883
Jumlah data terhapus        : 0

In [18]:
folder_tujuan = 'DatasetPreprocessDana' 

if not os.path.exists(folder_tujuan):
    os.makedirs(folder_tujuan)

path_output = os.path.join(folder_tujuan, 'Tahap4Preprocessing.csv')
data.to_csv(path_output, index=False, encoding='utf-8')
print(f"File berhasil disimpan di: {path_output}")
data.info()

File berhasil disimpan di: DatasetPreprocessDana\Tahap4Preprocessing.csv
<class 'pandas.core.frame.DataFrame'>
Index: 9883 entries, 0 to 10150
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Review text       9883 non-null   object
 1   clean_text        9883 non-null   object
 2   normalisasi_text  9883 non-null   object
 3   tokenize          9883 non-null   object
 4   stopword_removal  9883 non-null   object
 5   steming_data      9883 non-null   object
dtypes: object(6)
memory usage: 540.5+ KB