Karena yang akan digunakan hanya kolom full text atau isi ulasan maka disimpan file csv dengan isi kolom full text untuk meringankan beban komputasi

In [1]:
import os
import pandas as pd

# Membaca file dan menampilkan 5 data pertama
df = pd.read_csv("../../ScrapingData/hasilScrapUlasanAplikasiGopay.csv")
print(df.head())

                              Review id         Username  Rating  \
0  e1e6d78b-b9c6-4860-9d50-69176d865760  Pengguna Google       5
1  d8065c13-6a56-4ad9-a4b3-28871120704c  Pengguna Google       5
2  35b458a6-e101-4909-8d58-56cf69a609bc  Pengguna Google       5
3  9d50e390-6f48-443c-934a-ad74ff7c2e20  Pengguna Google       1
4  e2ec1c9a-d2a8-441c-8603-a6b9f7992922  Pengguna Google       1

                                         Review text                 Date
0                             baguss bangetzzzzzzzzz  2025-12-30 21:03:14
1  baik pelayan nan enya aman kalo transaksi ke m...  2025-12-30 21:01:31
2                                              bagus  2025-12-30 21:00:00
3  scan barcode terlalu bermasalah gagal teknis M...  2025-12-30 20:59:07
4  ini kok ga g ada konfir masi apa apa jol di po...  2025-12-30 20:58:19

In [2]:
df = df[["Review text"]]
print(df.tail())

                                             Review text
14995                                              Bagus
14996                           semoga gopay tambah jaya
14997                                        saat ini ok
14998                                             mantul
14999  tolong gopay saya keluar sendiri tidak bisa masuk

In [3]:
# Tentukan path folder tujuan
folder_tujuan = 'DatasetPreprocessGopay' 

# Pastikan folder tujuan sudah ada, jika belum maka buat folder tersebut
# Ini adalah langkah yang baik untuk menghindari error
if not os.path.exists(folder_tujuan):
    os.makedirs(folder_tujuan)

# Gabungkan path folder dengan nama file yang diinginkan
path_output = os.path.join(folder_tujuan, 'Tahap1IsiUlasan.csv')

# Simpan DataFrame ke path yang sudah ditentukan
df.to_csv(path_output, index=False, encoding='utf-8')

print(f"File berhasil disimpan di: {path_output}")

# Tetap tampilkan info DataFrame setelah menyimpan
df.info()

File berhasil disimpan di: DatasetPreprocessGopay\Tahap1IsiUlasan.csv
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Review text  15000 non-null  object
dtypes: object(1)
memory usage: 117.3+ KB

## Hapus data duplikat dan data kurang dari 3 huruf

In [4]:
import pandas as pd
import os

# --- PENGOLAHAN FILE ---

# 1. Tentukan nama file CSV yang akan diproses
nama_file_input = 'DatasetPreprocessGopay/Tahap1IsiUlasan.csv' # GANTI DENGAN NAMA FILE ANDA

# Pastikan file ada sebelum melanjutkan
if not os.path.exists(nama_file_input):
    print(f"Error: File tidak ditemukan di '{os.path.abspath(nama_file_input)}'")
else:
    # 2. Langsung baca satu file CSV ke dalam DataFrame
    print(f"Membaca file: '{nama_file_input}'")
    data = pd.read_csv(nama_file_input)

    print(f"\nJumlah baris sebelum menghapus duplikat: {len(data)}")

    # 3. Hapus baris duplikat berdasarkan kolom 'full_text'
    data.drop_duplicates(subset=['Review text'], inplace=True, keep='first')

    print(f"Jumlah baris setelah menghapus duplikat: {len(data)}")

    # --- PENYIMPANAN FILE ---

    # 4. Tentukan nama folder dan file output
    folder_tujuan = 'DatasetPreprocessGopay'
    
    # Tentukan path lengkap untuk file output
    nama_file_output = 'Tahap2HapusDuplikat.csv'
    path_output = os.path.join(folder_tujuan, nama_file_output)

    # 5. Simpan DataFrame yang sudah bersih ke file baru
    data.to_csv(path_output, index=False, encoding='utf-8')

    print(f"\nSukses! Duplikat telah dihapus dan file disimpan di:")
    print(f"'{path_output}'")

Membaca file: 'DatasetPreprocessGopay/Tahap1IsiUlasan.csv'

Jumlah baris sebelum menghapus duplikat: 15000
Jumlah baris setelah menghapus duplikat: 9324

Sukses! Duplikat telah dihapus dan file disimpan di:
'DatasetPreprocessGopay\Tahap2HapusDuplikat.csv'

In [5]:
import pandas as pd
import re
import os

# 1. Fungsi untuk menghapus kata dengan huruf <= 3
def hapus_kata_pendek(data):
    """
    Menghapus kata-kata yang panjang hurufnya <= 3.
    Contoh:
    'aku di rumah' -> 'rumah'
    'ini bagus banget' -> 'bagus banget'
    """
    if not isinstance(data, str):
        return ''
    
    # Hapus tanda baca supaya tidak mengganggu perhitungan panjang huruf
    teks_bersih = re.sub(r'[^\w\s]', '', data)
    
    # Pisahkan jadi kata-kata
    daftar_kata = teks_bersih.split()
    
    # Ambil hanya kata dengan panjang > 3 huruf
    kata_yang_disaring = [kata for kata in daftar_kata if len(kata) > 3]
    
    # Gabungkan kembali jadi kalimat
    return ' '.join(kata_yang_disaring)

# --- 2. Proses DataFrame ---
try:
    # Path file input
    path_input = os.path.join('DatasetPreprocessGopay','Tahap2HapusDuplikat.csv')
    data = pd.read_csv(path_input)
    
    print("File CSV berhasil dibaca. Berikut 5 baris pertama data asli:")
    print(data.head())
    print("-" * 50)
    
    # Ganti dengan nama kolom data kamu
    nama_kolom_asli = 'Review text'
    
    # Terapkan fungsi pembersihan
    data['teks_bersih'] = data[nama_kolom_asli].apply(hapus_kata_pendek)
    
    print("Fungsi berhasil diterapkan. Berikut hasilnya:")
    print(data[[nama_kolom_asli, 'teks_bersih']].head())
    print("-" * 50)
    
    # Simpan hasilnya ke file baru
    folder_tujuan = 'DatasetPreprocessGopay'
    nama_file_output = 'Tahap3HapusKurang3Huruf.csv'
    path_output = os.path.join(folder_tujuan, nama_file_output)
    
    data.to_csv(path_output, index=False, encoding='utf-8')
    
    print(f"DataFrame yang sudah bersih berhasil disimpan di: '{path_output}'")

except FileNotFoundError:
    print("Error: File tidak ditemukan. Mohon periksa kembali path file input Anda.")

File CSV berhasil dibaca. Berikut 5 baris pertama data asli:
                                         Review text
0                             baguss bangetzzzzzzzzz
1  baik pelayan nan enya aman kalo transaksi ke m...
2                                              bagus
3  scan barcode terlalu bermasalah gagal teknis M...
4  ini kok ga g ada konfir masi apa apa jol di po...
--------------------------------------------------
Fungsi berhasil diterapkan. Berikut hasilnya:
                                         Review text  \
0                             baguss bangetzzzzzzzzz
1  baik pelayan nan enya aman kalo transaksi ke m...
2                                              bagus
3  scan barcode terlalu bermasalah gagal teknis M...
4  ini kok ga g ada konfir masi apa apa jol di po...

                                         teks_bersih
0                             baguss bangetzzzzzzzzz
1              baik pelayan enya aman kalo transaksi
2                                              bagus
3  scan barcode terlalu bermasalah gagal teknis M...
4  konfir masi potong hedeuh jadi kapok nyimpen u...
--------------------------------------------------
DataFrame yang sudah bersih berhasil disimpan di: 'DatasetPreprocessGopay\Tahap3HapusKurang3Huruf.csv'

Ada beberapa tahapan pra pemrosesn yang saya lakukan, tetapi karena kolom yang akan saya pakai hanya kolom isi ulasan X saja atau kolom yang bernama "full_text" maka saya akan menyimpan kolom tersebut kedalam satu file terlebih dahulu agar meringankan beban komputasi data.Setelah dilakukan penghapusan kata kurang dari 3 huruf didapatkan kolom baru yaitu kolom "teks_bersih", selanjutnya adalah proses preprocessing. Beberapa tahapan yang saya lakukan sebagai berikut:

## 1. Casefolding
casefolding data atau biasa disebut dengan pembersihan data seprti menyamakan hurup menjadi huruf kecil semua, menghapus karakter khusus seperti ?!@#$, dan menghapus angka.

In [6]:
import re
import pandas as pd
import nltk
from nltk.corpus import stopwords
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory


#1. Casefolding data
def caseFolding(data, text_field, new_text_field_name):
    # Mengubah huruf kapital menjadi kecil
    data[new_text_field_name] = data[text_field].str.lower()
    # Menghapus karakter seperti @, #
    data[new_text_field_name] = data[new_text_field_name].apply(lambda elem: re.sub(r"(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)|^rt|http.+?", "", elem))
    # Menghapus angka
    data[new_text_field_name] = data[new_text_field_name].apply(lambda elem: re.sub(r"\d+", "", elem))
    return data

data_clean = caseFolding(data, 'teks_bersih', 'clean_text')
data_clean.head(10)

,Review text,teks_bersih,clean_text
0,baguss bangetzzzzzzzzz,baguss bangetzzzzzzzzz,baguss bangetzzzzzzzzz
1,baik pelayan nan enya aman kalo transaksi ke m...,baik pelayan enya aman kalo transaksi,baik pelayan enya aman kalo transaksi
2,bagus,bagus,bagus
3,scan barcode terlalu bermasalah gagal teknis M...,scan barcode terlalu bermasalah gagal teknis M...,scan barcode terlalu bermasalah gagal teknis m...
4,ini kok ga g ada konfir masi apa apa jol di po...,konfir masi potong hedeuh jadi kapok nyimpen u...,konfir masi potong hedeuh jadi kapok nyimpen u...
5,sangat bagus,sangat bagus,sangat bagus
6,"susah amat verifikasinya, udah puluhan kali co...",susah amat verifikasinya udah puluhan kali cob...,susah amat verifikasinya udah puluhan kali cob...
7,nice apk,nice,nice
8,i like,like,like
9,suka nih,suka,suka

## 2. Normalisasi Teks

In [10]:
# 2. Normalisasi kata tidak baku
def replace_taboo_words(text, kamus_tidak_baku):
    if isinstance(text, str):
        words = text.split()
        replaced_words = []
        kalimat_baku = []
        kata_diganti = []
        kata_tidak_baku_hash = []

        for word in words:
            if word in kamus_tidak_baku:
                baku_word = kamus_tidak_baku[word]
                if isinstance(baku_word, str) and all(char.isalpha() or char.isspace() for char in baku_word):
                    replaced_words.append(baku_word)
                    kalimat_baku.append(baku_word)
                    kata_diganti.append(word)
                    kata_tidak_baku_hash.append(hash(word))
                else:
                    replaced_words.append(word)
            else:
                replaced_words.append(word)

        replaced_text = ' '.join(replaced_words)
        return replaced_text, kalimat_baku, kata_diganti, kata_tidak_baku_hash
    else:
        return "", [], [], []

# Load kamus data
kamus_data = pd.read_excel("../../kamus/kamuskatabaku.xlsx")
kamus_tidak_baku = dict(zip(kamus_data["tidak_baku"], kamus_data["kata_baku"]))
results = data["clean_text"].apply(lambda x: replace_taboo_words(x, kamus_tidak_baku))
data["normalisasi_text"], data["kata_baku"], data["kata_tidak_baku"], data["kata_tidak_baku_Hash"] = zip(*results)
data[['Review text', 'teks_bersih', 'clean_text', 'normalisasi_text']].head(10)

,Review text,teks_bersih,clean_text,normalisasi_text
0,baguss bangetzzzzzzzzz,baguss bangetzzzzzzzzz,baguss bangetzzzzzzzzz,bagus bangetzzzzzzzzz
1,baik pelayan nan enya aman kalo transaksi ke m...,baik pelayan enya aman kalo transaksi,baik pelayan enya aman kalo transaksi,baik pelayan enya aman kalau transaksi
2,bagus,bagus,bagus,bagus
3,scan barcode terlalu bermasalah gagal teknis M...,scan barcode terlalu bermasalah gagal teknis M...,scan barcode terlalu bermasalah gagal teknis m...,scan barcode terlalu bermasalah gagal teknis m...
4,ini kok ga g ada konfir masi apa apa jol di po...,konfir masi potong hedeuh jadi kapok nyimpen u...,konfir masi potong hedeuh jadi kapok nyimpen u...,konfir masih potong hedeuh jadi kapok menyimpa...
5,sangat bagus,sangat bagus,sangat bagus,sangat bagus
6,"susah amat verifikasinya, udah puluhan kali co...",susah amat verifikasinya udah puluhan kali cob...,susah amat verifikasinya udah puluhan kali cob...,susah amat verifikasinya sudah puluhan kali co...
7,nice apk,nice,nice,nice
8,i like,like,like,like
9,suka nih,suka,suka,suka

## 3. Tokenizing

In [11]:
# 3. tokenizing (memisahkan teks menjadi potongan potongan)

def tokenize(text):
    tokens = text.split()
    return tokens

data["tokenize"] = data["normalisasi_text"].apply(tokenize)
data.head(10)

,Review text,teks_bersih,clean_text,normalisasi_text,kata_baku,kata_tidak_baku,kata_tidak_baku_Hash,tokenize
0,baguss bangetzzzzzzzzz,baguss bangetzzzzzzzzz,baguss bangetzzzzzzzzz,bagus bangetzzzzzzzzz,[bagus],[baguss],[-6901454843429905671],"[bagus, bangetzzzzzzzzz]"
1,baik pelayan nan enya aman kalo transaksi ke m...,baik pelayan enya aman kalo transaksi,baik pelayan enya aman kalo transaksi,baik pelayan enya aman kalau transaksi,[kalau],[kalo],[-503019375705883942],"[baik, pelayan, enya, aman, kalau, transaksi]"
2,bagus,bagus,bagus,bagus,[],[],[],[bagus]
3,scan barcode terlalu bermasalah gagal teknis M...,scan barcode terlalu bermasalah gagal teknis M...,scan barcode terlalu bermasalah gagal teknis m...,scan barcode terlalu bermasalah gagal teknis m...,[],[],[],"[scan, barcode, terlalu, bermasalah, gagal, te..."
4,ini kok ga g ada konfir masi apa apa jol di po...,konfir masi potong hedeuh jadi kapok nyimpen u...,konfir masi potong hedeuh jadi kapok nyimpen u...,konfir masih potong hedeuh jadi kapok menyimpa...,"[masih, menyimpan, hilang]","[masi, nyimpen, ilang]","[-4143172469885334554, -3208763987271915779, 4...","[konfir, masih, potong, hedeuh, jadi, kapok, m..."
5,sangat bagus,sangat bagus,sangat bagus,sangat bagus,[],[],[],"[sangat, bagus]"
6,"susah amat verifikasinya, udah puluhan kali co...",susah amat verifikasinya udah puluhan kali cob...,susah amat verifikasinya udah puluhan kali cob...,susah amat verifikasinya sudah puluhan kali co...,[sudah],[udah],[7529242483300466612],"[susah, amat, verifikasinya, sudah, puluhan, k..."
7,nice apk,nice,nice,nice,[],[],[],[nice]
8,i like,like,like,like,[],[],[],[like]
9,suka nih,suka,suka,suka,[],[],[],[suka]

## 4. Stopword Removal

In [12]:
#  4. Stopword removal (menghapus kata umum atau sambung contoh yang, di, dan)

# Unduh stopwords bahasa Indonesia
nltk.download('stopwords')

# Mendapatkan stopwords bahasa Indonesia
stop_words = stopwords.words('indonesian')
def remove_stopwords(text):
    return [word for word in text if word not in stop_words]

data['stopword_removal'] = data['tokenize'].apply(lambda x: remove_stopwords(x))
data.head(10)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,Review text,teks_bersih,clean_text,normalisasi_text,kata_baku,kata_tidak_baku,kata_tidak_baku_Hash,tokenize,stopword_removal
0,baguss bangetzzzzzzzzz,baguss bangetzzzzzzzzz,baguss bangetzzzzzzzzz,bagus bangetzzzzzzzzz,[bagus],[baguss],[-6901454843429905671],"[bagus, bangetzzzzzzzzz]","[bagus, bangetzzzzzzzzz]"
1,baik pelayan nan enya aman kalo transaksi ke m...,baik pelayan enya aman kalo transaksi,baik pelayan enya aman kalo transaksi,baik pelayan enya aman kalau transaksi,[kalau],[kalo],[-503019375705883942],"[baik, pelayan, enya, aman, kalau, transaksi]","[pelayan, enya, aman, transaksi]"
2,bagus,bagus,bagus,bagus,[],[],[],[bagus],[bagus]
3,scan barcode terlalu bermasalah gagal teknis M...,scan barcode terlalu bermasalah gagal teknis M...,scan barcode terlalu bermasalah gagal teknis m...,scan barcode terlalu bermasalah gagal teknis m...,[],[],[],"[scan, barcode, terlalu, bermasalah, gagal, te...","[scan, barcode, bermasalah, gagal, teknis, mul..."
4,ini kok ga g ada konfir masi apa apa jol di po...,konfir masi potong hedeuh jadi kapok nyimpen u...,konfir masi potong hedeuh jadi kapok nyimpen u...,konfir masih potong hedeuh jadi kapok menyimpa...,"[masih, menyimpan, hilang]","[masi, nyimpen, ilang]","[-4143172469885334554, -3208763987271915779, 4...","[konfir, masih, potong, hedeuh, jadi, kapok, m...","[konfir, potong, hedeuh, kapok, menyimpan, uan..."
5,sangat bagus,sangat bagus,sangat bagus,sangat bagus,[],[],[],"[sangat, bagus]",[bagus]
6,"susah amat verifikasinya, udah puluhan kali co...",susah amat verifikasinya udah puluhan kali cob...,susah amat verifikasinya udah puluhan kali cob...,susah amat verifikasinya sudah puluhan kali co...,[sudah],[udah],[7529242483300466612],"[susah, amat, verifikasinya, sudah, puluhan, k...","[susah, verifikasinya, puluhan, kali, coba, ga..."
7,nice apk,nice,nice,nice,[],[],[],[nice],[nice]
8,i like,like,like,like,[],[],[],[like],[like]
9,suka nih,suka,suka,suka,[],[],[],[suka],[suka]

## 5. Steming

In [13]:
 # Step 5: Stemming

factory = StemmerFactory()
stemmer = factory.create_stemmer()

def stem_text(text):
    return [stemmer.stem(word) for word in text]

data['steming_data'] = data['stopword_removal'].apply(lambda x:' '.join(stem_text(x)))
data.head(10)

,Review text,teks_bersih,clean_text,normalisasi_text,kata_baku,kata_tidak_baku,kata_tidak_baku_Hash,tokenize,stopword_removal,steming_data
0,baguss bangetzzzzzzzzz,baguss bangetzzzzzzzzz,baguss bangetzzzzzzzzz,bagus bangetzzzzzzzzz,[bagus],[baguss],[-6901454843429905671],"[bagus, bangetzzzzzzzzz]","[bagus, bangetzzzzzzzzz]",bagus bangetzzzzzzzzz
1,baik pelayan nan enya aman kalo transaksi ke m...,baik pelayan enya aman kalo transaksi,baik pelayan enya aman kalo transaksi,baik pelayan enya aman kalau transaksi,[kalau],[kalo],[-503019375705883942],"[baik, pelayan, enya, aman, kalau, transaksi]","[pelayan, enya, aman, transaksi]",layan enya aman transaksi
2,bagus,bagus,bagus,bagus,[],[],[],[bagus],[bagus],bagus
3,scan barcode terlalu bermasalah gagal teknis M...,scan barcode terlalu bermasalah gagal teknis M...,scan barcode terlalu bermasalah gagal teknis m...,scan barcode terlalu bermasalah gagal teknis m...,[],[],[],"[scan, barcode, terlalu, bermasalah, gagal, te...","[scan, barcode, bermasalah, gagal, teknis, mul...",scan barcode masalah gagal teknis mulu payah
4,ini kok ga g ada konfir masi apa apa jol di po...,konfir masi potong hedeuh jadi kapok nyimpen u...,konfir masi potong hedeuh jadi kapok nyimpen u...,konfir masih potong hedeuh jadi kapok menyimpa...,"[masih, menyimpan, hilang]","[masi, nyimpen, ilang]","[-4143172469885334554, -3208763987271915779, 4...","[konfir, masih, potong, hedeuh, jadi, kapok, m...","[konfir, potong, hedeuh, kapok, menyimpan, uan...",konfir potong hedeuh kapok simpan uang bahaya ...
5,sangat bagus,sangat bagus,sangat bagus,sangat bagus,[],[],[],"[sangat, bagus]",[bagus],bagus
6,"susah amat verifikasinya, udah puluhan kali co...",susah amat verifikasinya udah puluhan kali cob...,susah amat verifikasinya udah puluhan kali cob...,susah amat verifikasinya sudah puluhan kali co...,[sudah],[udah],[7529242483300466612],"[susah, amat, verifikasinya, sudah, puluhan, k...","[susah, verifikasinya, puluhan, kali, coba, ga...",susah verifikasi puluh kali coba gagal udha la...
7,nice apk,nice,nice,nice,[],[],[],[nice],[nice],nice
8,i like,like,like,like,[],[],[],[like],[like],like
9,suka nih,suka,suka,suka,[],[],[],[suka],[suka],suka

Cek missing value setelah dilakukan semua tahapan preprocessing

In [14]:
data.isnull().sum()

Review text             0
teks_bersih             0
clean_text              0
normalisasi_text        0
kata_baku               0
kata_tidak_baku         0
kata_tidak_baku_Hash    0
tokenize                0
stopword_removal        0
steming_data            0
dtype: int64

In [15]:
import pandas as pd

data = pd.DataFrame(data[["Review text","clean_text","normalisasi_text","tokenize","stopword_removal","steming_data"]])
data.head(10)

,Review text,clean_text,normalisasi_text,tokenize,stopword_removal,steming_data
0,baguss bangetzzzzzzzzz,baguss bangetzzzzzzzzz,bagus bangetzzzzzzzzz,"[bagus, bangetzzzzzzzzz]","[bagus, bangetzzzzzzzzz]",bagus bangetzzzzzzzzz
1,baik pelayan nan enya aman kalo transaksi ke m...,baik pelayan enya aman kalo transaksi,baik pelayan enya aman kalau transaksi,"[baik, pelayan, enya, aman, kalau, transaksi]","[pelayan, enya, aman, transaksi]",layan enya aman transaksi
2,bagus,bagus,bagus,[bagus],[bagus],bagus
3,scan barcode terlalu bermasalah gagal teknis M...,scan barcode terlalu bermasalah gagal teknis m...,scan barcode terlalu bermasalah gagal teknis m...,"[scan, barcode, terlalu, bermasalah, gagal, te...","[scan, barcode, bermasalah, gagal, teknis, mul...",scan barcode masalah gagal teknis mulu payah
4,ini kok ga g ada konfir masi apa apa jol di po...,konfir masi potong hedeuh jadi kapok nyimpen u...,konfir masih potong hedeuh jadi kapok menyimpa...,"[konfir, masih, potong, hedeuh, jadi, kapok, m...","[konfir, potong, hedeuh, kapok, menyimpan, uan...",konfir potong hedeuh kapok simpan uang bahaya ...
5,sangat bagus,sangat bagus,sangat bagus,"[sangat, bagus]",[bagus],bagus
6,"susah amat verifikasinya, udah puluhan kali co...",susah amat verifikasinya udah puluhan kali cob...,susah amat verifikasinya sudah puluhan kali co...,"[susah, amat, verifikasinya, sudah, puluhan, k...","[susah, verifikasinya, puluhan, kali, coba, ga...",susah verifikasi puluh kali coba gagal udha la...
7,nice apk,nice,nice,[nice],[nice],nice
8,i like,like,like,[like],[like],like
9,suka nih,suka,suka,[suka],[suka],suka

Karena setelah dilakukan preprocessing terdapat string yang didalamnya kosong atau tidak berisi data maka dilakukan penghapusan

In [17]:
# jumlah data sebelum
before = len(data)

# hapus teks kosong
data = data[data["steming_data"].str.strip() != ""]

# jumlah data sesudah
after = len(data)

print(f"Jumlah data sebelum dihapus : {before}")
print(f"Jumlah data sesudah dihapus : {after}")
print(f"Jumlah data terhapus        : {before - after}")

Jumlah data sebelum dihapus : 9324
Jumlah data sesudah dihapus : 9012
Jumlah data terhapus        : 312

In [18]:
folder_tujuan = 'DatasetPreprocessGopay' 

if not os.path.exists(folder_tujuan):
    os.makedirs(folder_tujuan)

path_output = os.path.join(folder_tujuan, 'Tahap4Preprocessing.csv')
data.to_csv(path_output, index=False, encoding='utf-8')
print(f"File berhasil disimpan di: {path_output}")
data.info()

File berhasil disimpan di: DatasetPreprocessGopay\Tahap4Preprocessing.csv
<class 'pandas.core.frame.DataFrame'>
Index: 9012 entries, 0 to 9323
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Review text       9012 non-null   object
 1   clean_text        9012 non-null   object
 2   normalisasi_text  9012 non-null   object
 3   tokenize          9012 non-null   object
 4   stopword_removal  9012 non-null   object
 5   steming_data      9012 non-null   object
dtypes: object(6)
memory usage: 492.8+ KB