## Scraping ulasan aplikasi Gopay

In [10]:
from google_play_scraper import app, reviews, Sort
import pandas as pd
def getReviews(app_id, lang="id", count=15000, sort=Sort.NEWEST, filter_score_with=None, filter_device_with=None, continuation_token=None):
    try:
        result, continuation_token = reviews(
            app_id,
            lang=lang,
            country="id",
            sort=sort,
            count=count,
            filter_score_with=filter_score_with,
            filter_device_with=filter_device_with,
            continuation_token=continuation_token
        )
        return result, continuation_token
    except Exception as e:
        print("Error: ", e)
        return None, None

# app_id = "com.id.go.bawaslu.siwaslu2024"
app_id = "com.gojek.gopay"
reviews, continuation_token = getReviews(app_id)

if reviews is not None:
    print("Jumlah ulasan: ", len(reviews))
    if len(reviews) > 0:
        print("Contoh ulasan:")
        print(reviews[0])
else:
    print("Tidak ada ulasan")

Jumlah ulasan:  15000
Contoh ulasan:
{'reviewId': 'e1e6d78b-b9c6-4860-9d50-69176d865760', 'userName': 'Pengguna Google', 'userImage': 'https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g', 'content': 'baguss bangetzzzzzzzzz', 'score': 5, 'thumbsUpCount': 0, 'reviewCreatedVersion': '2.0.3', 'at': datetime.datetime(2025, 12, 30, 21, 3, 14), 'replyContent': None, 'repliedAt': None, 'appVersion': '2.0.3'}

In [11]:
import csv

def eksporDataKeCsv(reviews, namaFile = "hasilScrapUlasanAplikasiGopay.csv"):
    if reviews:
        fieldnames = ["Review id","Username", "Rating", "Review text", "Date"]

        with open(namaFile, mode="w", newline="", encoding="utf-8") as csv_file:
            writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
            writer.writeheader()

            for review in reviews:
                writer.writerow({
                    "Review id" :review["reviewId"],
                    "Username" :review["userName"],
                    "Rating" :review["score"],
                    "Review text" :review["content"],
                    "Date" :review["at"]
                })
        print(f"Data berhasil diekspor ke {namaFile}")
    else:
        print("Data tidak dapat diekspor")

eksporDataKeCsv(reviews)

Data berhasil diekspor ke hasilScrapUlasanAplikasiGopay.csv

In [12]:
data = pd.read_csv("hasilScrapUlasanAplikasiGopay.csv")

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Review id    15000 non-null  object
 1   Username     15000 non-null  object
 2   Rating       15000 non-null  int64
 3   Review text  15000 non-null  object
 4   Date         15000 non-null  object
dtypes: int64(1), object(4)
memory usage: 586.1+ KB

In [13]:
data.head()

,Review id,Username,Rating,Review text,Date
0,e1e6d78b-b9c6-4860-9d50-69176d865760,Pengguna Google,5,baguss bangetzzzzzzzzz,2025-12-30 21:03:14
1,d8065c13-6a56-4ad9-a4b3-28871120704c,Pengguna Google,5,baik pelayan nan enya aman kalo transaksi ke m...,2025-12-30 21:01:31
2,35b458a6-e101-4909-8d58-56cf69a609bc,Pengguna Google,5,bagus,2025-12-30 21:00:00
3,9d50e390-6f48-443c-934a-ad74ff7c2e20,Pengguna Google,1,scan barcode terlalu bermasalah gagal teknis M...,2025-12-30 20:59:07
4,e2ec1c9a-d2a8-441c-8603-a6b9f7992922,Pengguna Google,1,ini kok ga g ada konfir masi apa apa jol di po...,2025-12-30 20:58:19

## Scrap ulasan aplikasi shopeepay

In [14]:
from google_play_scraper import app, reviews, Sort
import pandas as pd
def getReviews(app_id, lang="id", count=15000, sort=Sort.NEWEST, filter_score_with=None, filter_device_with=None, continuation_token=None):
    try:
        result, continuation_token = reviews(
            app_id,
            lang=lang,
            country="id",
            sort=sort,
            count=count,
            filter_score_with=filter_score_with,
            filter_device_with=filter_device_with,
            continuation_token=continuation_token
        )
        return result, continuation_token
    except Exception as e:
        print("Error: ", e)
        return None, None

# app_id = "com.id.go.bawaslu.siwaslu2024"
app_id = "com.shopeepay.id"
reviews, continuation_token = getReviews(app_id)

if reviews is not None:
    print("Jumlah ulasan: ", len(reviews))
    if len(reviews) > 0:
        print("Contoh ulasan:")
        print(reviews[0])
else:
    print("Tidak ada ulasan")

Jumlah ulasan:  15000
Contoh ulasan:
{'reviewId': 'cadcde91-9403-4c8d-b8b1-fd0105c9587e', 'userName': 'Pengguna Google', 'userImage': 'https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g', 'content': 'Di coba dulu. Kalau memuaskan, bisa diberikan 5 bintang.', 'score': 4, 'thumbsUpCount': 0, 'reviewCreatedVersion': '1.45.09', 'at': datetime.datetime(2025, 12, 30, 21, 4, 3), 'replyContent': 'Hi Kak BAKU. Terima kasih telah menggunakan ShopeePay. Mari cek aplikasi ShopeePay karena banyak fitur yg mempermudah keseharian kakak, seperti pembelian pulsa, paket data, pembayaran tagihan listrik dan pembayaran lainnya. Jika kakak memiliki pertanyaan seputar ShopeePay, mohon DM kami di Instagram @ShopeePay_ID. Semoga harimu menyenangkan. ^CS', 'repliedAt': datetime.datetime(2025, 12, 31, 11, 45, 8), 'appVersion': '1.45.09'}

In [15]:
import csv

def eksporDataKeCsv(reviews, namaFile = "hasilScrapUlasanAplikasishopeepay.csv"):
    if reviews:
        fieldnames = ["Review id","Username", "Rating", "Review text", "Date"]

        with open(namaFile, mode="w", newline="", encoding="utf-8") as csv_file:
            writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
            writer.writeheader()

            for review in reviews:
                writer.writerow({
                    "Review id" :review["reviewId"],
                    "Username" :review["userName"],
                    "Rating" :review["score"],
                    "Review text" :review["content"],
                    "Date" :review["at"]
                })
        print(f"Data berhasil diekspor ke {namaFile}")
    else:
        print("Data tidak dapat diekspor")

eksporDataKeCsv(reviews)

Data berhasil diekspor ke hasilScrapUlasanAplikasishopeepay.csv

In [16]:
data = pd.read_csv("hasilScrapUlasanAplikasishopeepay.csv")

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Review id    15000 non-null  object
 1   Username     15000 non-null  object
 2   Rating       15000 non-null  int64
 3   Review text  15000 non-null  object
 4   Date         15000 non-null  object
dtypes: int64(1), object(4)
memory usage: 586.1+ KB

In [17]:
data.head()

,Review id,Username,Rating,Review text,Date
0,cadcde91-9403-4c8d-b8b1-fd0105c9587e,Pengguna Google,4,"Di coba dulu. Kalau memuaskan, bisa diberikan ...",2025-12-30 21:04:03
1,195cc76b-1bee-4484-975e-689deea11a7e,Pengguna Google,5,mantap murah,2025-12-30 21:03:07
2,cdd95223-f59e-44d8-af2f-847a86e9380a,Pengguna Google,4,mantabb,2025-12-30 20:56:16
3,ca8b22c3-b610-44d7-b407-6c52fb0edc98,Pengguna Google,5,bisa bayar pulsa dan juga belanja,2025-12-30 20:50:07
4,46ac09dc-dd99-4a3d-ade5-f3aebc0979cf,Pengguna Google,5,kenapa pas transaksi gagal mulu min,2025-12-30 20:47:44

## Scrap ulasan aplikasi dana

In [18]:
from google_play_scraper import app, reviews, Sort
import pandas as pd
def getReviews(app_id, lang="id", count=15000, sort=Sort.NEWEST, filter_score_with=None, filter_device_with=None, continuation_token=None):
    try:
        result, continuation_token = reviews(
            app_id,
            lang=lang,
            country="id",
            sort=sort,
            count=count,
            filter_score_with=filter_score_with,
            filter_device_with=filter_device_with,
            continuation_token=continuation_token
        )
        return result, continuation_token
    except Exception as e:
        print("Error: ", e)
        return None, None

# app_id = "com.id.go.bawaslu.siwaslu2024"
app_id = "id.dana"
reviews, continuation_token = getReviews(app_id)

if reviews is not None:
    print("Jumlah ulasan: ", len(reviews))
    if len(reviews) > 0:
        print("Contoh ulasan:")
        print(reviews[0])
else:
    print("Tidak ada ulasan")

Jumlah ulasan:  15000
Contoh ulasan:
{'reviewId': 'eb54a202-65d5-497f-bcd5-2aaef78905ae', 'userName': 'Pengguna Google', 'userImage': 'https://play-lh.googleusercontent.com/EGemoI2NTXmTsBVtJqk8jxF9rh8ApRWfsIMQSt2uE4OcpQqbFu7f7NbTK05lx80nuSijCz7sc3a277R67g', 'content': 'keren sekali', 'score': 5, 'thumbsUpCount': 0, 'reviewCreatedVersion': '2.107.0', 'at': datetime.datetime(2025, 12, 30, 21, 4, 51), 'replyContent': None, 'repliedAt': None, 'appVersion': '2.107.0'}

In [19]:
import csv

def eksporDataKeCsv(reviews, namaFile = "hasilScrapUlasanAplikasidana.csv"):
    if reviews:
        fieldnames = ["Review id","Username", "Rating", "Review text", "Date"]

        with open(namaFile, mode="w", newline="", encoding="utf-8") as csv_file:
            writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
            writer.writeheader()

            for review in reviews:
                writer.writerow({
                    "Review id" :review["reviewId"],
                    "Username" :review["userName"],
                    "Rating" :review["score"],
                    "Review text" :review["content"],
                    "Date" :review["at"]
                })
        print(f"Data berhasil diekspor ke {namaFile}")
    else:
        print("Data tidak dapat diekspor")

eksporDataKeCsv(reviews)

Data berhasil diekspor ke hasilScrapUlasanAplikasidana.csv

In [20]:
data = pd.read_csv("hasilScrapUlasanAplikasidana.csv")

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Review id    15000 non-null  object
 1   Username     15000 non-null  object
 2   Rating       15000 non-null  int64
 3   Review text  15000 non-null  object
 4   Date         15000 non-null  object
dtypes: int64(1), object(4)
memory usage: 586.1+ KB

In [21]:
data.head()

,Review id,Username,Rating,Review text,Date
0,eb54a202-65d5-497f-bcd5-2aaef78905ae,Pengguna Google,5,keren sekali,2025-12-30 21:04:51
1,acacd759-d766-48bc-95a4-ec5e7e54443b,Pengguna Google,5,fitur dana cicil tidak bisa di akses padahal s...,2025-12-30 21:04:47
2,0d6208ff-16a0-40fe-8568-6bf8cc8d5ef6,Pengguna Google,5,sangat baik,2025-12-30 21:04:10
3,d1e8c879-6f6d-4a0d-bead-d41b6838c4de,Pengguna Google,4,"saya sempet kesel waktu itu, jadi saya beli pa...",2025-12-30 21:03:43
4,5fa08dbd-8ed2-4155-aa8e-1eb59eb2e181,Pengguna Google,4,"Belum menerima hasil,..",2025-12-30 21:03:14